"""Added Youtube content

Revision ID: 19e5dd1360a2
Revises: aac7ae7db672
Create Date: 2021-07-13 21:05:37.230085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e5dd1360a2'
down_revision = 'aac7ae7db672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('you_tube_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('channel_title', sa.String(length=140), nullable=True),
    sa.Column('channel_url', sa.String(length=140), nullable=True),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('you_tube_content')
    # ### end Alembic commands ###
