"""Add hidden for content

Revision ID: 1ee3fcaec4a2
Revises: f5463b6c0070
Create Date: 2021-08-03 18:37:48.233194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee3fcaec4a2'
down_revision = 'f5463b6c0070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    # ### end Alembic commands ###
