"""Added youtube contents

Revision ID: 4b675ae7bc64
Revises: aac7ae7db672
Create Date: 2021-07-14 09:09:21.380908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b675ae7bc64'
down_revision = 'aac7ae7db672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('you_tube_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('channel_title', sa.String(length=140), nullable=True),
    sa.Column('channel_url', sa.String(length=140), nullable=True),
    sa.Column('image_url', sa.String(length=100), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('you_tube_content')
    # ### end Alembic commands ###
