"""Added user profile pic

Revision ID: 7454ab892818
Revises: 4b675ae7bc64
Create Date: 2021-07-26 22:01:16.068920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7454ab892818'
down_revision = '4b675ae7bc64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imgsrc', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('imgsrc')

    # ### end Alembic commands ###
