"""Added Youtube content foreign key

Revision ID: 7caf9e004a4e
Revises: 19e5dd1360a2
Create Date: 2021-07-13 21:08:26.975076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7caf9e004a4e'
down_revision = '19e5dd1360a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('you_tube_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'module', ['module_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('you_tube_content', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('module_id')

    # ### end Alembic commands ###
