"""Added course profile pics

Revision ID: 83d8ec9ebda9
Revises: 7454ab892818
Create Date: 2021-07-27 19:05:24.104324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d8ec9ebda9'
down_revision = '7454ab892818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profileimg', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('profileimg')

    # ### end Alembic commands ###
