"""Removed Youtube Content

Revision ID: 9f7957da5d5a
Revises: 83d8ec9ebda9
Create Date: 2021-07-28 19:23:39.941123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7957da5d5a'
down_revision = '83d8ec9ebda9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('you_tube_content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('you_tube_content',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=True),
    sa.Column('description', sa.VARCHAR(length=240), nullable=True),
    sa.Column('url', sa.VARCHAR(length=140), nullable=True),
    sa.Column('channel_title', sa.VARCHAR(length=140), nullable=True),
    sa.Column('channel_url', sa.VARCHAR(length=140), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=100), nullable=True),
    sa.Column('module_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
